#==============================================================================
# Copyright (C) 2017 Stephen F. Norledge and Alces Flight Ltd.
#
# This file is part of Alces Launch.
#
# All rights reserved, see LICENSE.txt.
#==============================================================================

source 'http://rubygems.org'
ruby ENV['ALCES_RUBY_VERSION'] || '2.3.1'

rails_version                  = '~>  5.0.2'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

##################################
# The bits of Ruby-on-Rails we use
##################################
gem                'activemodel', rails_version
gem                'activesupport', rails_version
gem                 'actionmailer', rails_version
gem                   'actionpack', rails_version
gem                     'railties', rails_version


##################################
# Database access
##################################
gem 'sqlite3'

##################################
# Application server
##################################
gem 'puma', '~> 3.0'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

##################################
# Testing
##################################
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  # gem 'byebug', platform: :mri
end

##################################
# Development
##################################
group :development do
  gem 'listen', '~> 3.0.5'
  gem 'foreman'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
