web: bundle exec puma -C config/puma.rb config.ru
worker: bundle exec shoryuken start --rails --verbose --pidfile ./tmp/shoryuken.pid --concurrency ${WORKER_CONCURRENCY} --delay ${WORKER_DELAY} --queues ${ACTIVE_JOB_QUEUE_NAME_PREFIX}_default
