./flight-launch-token-generator.html: ./flight-launch-token-generator.html.erb *.txt
	ruby -rerb -rjson -e "puts ERB.new(File.read('./flight-launch-token-generator.html.erb')).result" > ./flight-launch-token-generator.html
